### ISSUE TITLE
InvalidArgument=Value of '0' is not valid for 'index'

### ISSUE THREAD

**Issue by KhunDoug** [Revan654/staxrip#19]
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
   at StaxRip.FiltersListView.RemoveClick() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Controls\FiltersListView.vb:line 236
   at StaxRip.UI.ActionMenuItem.OnClick(EventArgs e) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\UI\Menu Types.vb:line 519
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Revan654** [comment]
I need the logs, system logs are useless without knowing what your were trying to do.
