### ISSUE TITLE
Video encoding using x265 2.9+2 failed with exit code: -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by OnbekendHH** [Revan654/staxrip#23]
Hello Everyone...

Starting a few days ago, I've been getting StaxRip crashes only when using the Option/Preset "-grain". I can't figure out, what's the cause. Before, it worked like a charm. Here is the error:

Thanks for any help!

Greetings.

OnbekendHH

**Error Video encoding using x265 2.9+2 (1.9.0.0)

Video encoding using x265 2.9+2 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: The instruction at 0xp referenced memory at 0xp. The memory could not be s.**

------------------- Video encoding using x265 2.9+2 -------------------

"C:\Other Apps\StaxRip_1.9.0.0_x64\Apps\avs2pipemod\avs2pipemod64.exe" -y4mp "D:\StaxRip_Temp\Reprisal (2018)_temp\Reprisal (2018)_temp.avs" | "C:\Other Apps\x265\x265-2.9+2-7e978ed-stable_gcc82-AVX2\x265.exe" --crf 16 --preset slow --tune grain --profile main10 --level-idc 6.1 --output-depth 10 --dynamic-rd 4 --amp --b-intra --cu-lossless --ssim-rd --qpmax 23 --crf-max 19 --vbv-bufsize 120000 --vbv-maxrate 120000 --cplxblur 0 --aq-motion --subme 4 --weightb --bframes 16 --bframe-bias 100 --rc-lookahead 30 --lookahead-slices 1 --lookahead-threads 1 --ref 6 --keyint 720 --no-open-gop --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --hash 2 --repeat-headers --hrd --aud --vui-timing-info --vui-hrd-info --opt-qp-pps --opt-ref-list-length-pps --sao --limit-sao --sao-non-deblock --frames 128281 --y4m --output "D:\StaxRip_Temp\Reprisal (2018)_temp\Reprisal (2018)_temp_out.hevc" -

avs2pipemod[info]: writing 128281 frames of 24000/1001 fps, 1920x1040,
sar 0:0, YUV-420-planar-10bit progressive video.
y4m [info]: 1920x1040 fps 24000/1001 i420p10 unknown frame count
raw [info]: output file: D:\StaxRip_Temp\Reprisal (2018)_temp\Reprisal (2018)_temp_out.hevc
x265 [info]: HEVC encoder version 2.9+2-7e978ed93d60
x265 [info]: build info [Windows][GCC 8.2.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: Dynamic-rd disabled, requires RD <= 4, VBV and aq-mode enabled
x265 [info]: Main 10 profile, Level-6.1 (Main tier)
x265 [info]: Thread pool created using 11 threads
x265 [info]: Slices : 1
x265 [info]: frame threads / pool features : 3 / wpp(17 rows)
x265 [info]: Thread pool created using 1 threads
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge : star / 57 / 4 / 3
x265 [info]: Keyframe min / max / scenecut / bias: 23 / 720 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt : 30 / 16 / 2
x265 [info]: b-pyramid / weightp / weightb : 1 / 1 / 1
x265 [info]: References / ref-limit cu / depth : 6 / on / on
x265 [info]: Rate Control / qCompress : CRF-16.0 / 0.60
x265 [info]: VBV/HRD buffer / max-rate / init : 120000 / 120000 / 0.900
x265 [info]: tools: rect amp limit-modes rd=4 ssim-rd rdoq=2 psy-rdoq=10.00
x265 [info]: tools: cu-lossless signhide tmvp b-intra strong-intra-smoothing
x265 [info]: tools: lslices=1 lthreads=1 deblock sao-non-deblock
**avs2pipemod[info]: finished, wrote 91 frames [0%].
avs2pipemod[info]: total elapsed time is 7.843 sec.
avs2pipemod[error]: only wrote 91 of 128281 frames.

at StaxRip.Proc.Start() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\Proc.vb:line 338
at StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Encoding\x265Enc.vb:line 65
at StaxRip.x265Enc.Encode() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Encoding\x265Enc.vb:line 41
at StaxRip.GlobalClass.ProcessVideo() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\GlobalClass.vb:line 231
at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.b__0()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at StaxRip.GlobalClass.ProcessJob(String jobPath) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\GlobalClass.vb:line 138**

**Comment by Revan654** [comment]
You using a x265 build that has not been tested with StaxRip yet.

I would also make sure your CPU can handle the x265 build your using.

**Comment by OnbekendHH** [comment]
Hello Revan654,

thank you very much for the help so far.

I am still having the issue described above, being the following error when using **x265 Preset Grain**:
Not using Preset Grain results in no error.

```
---------------- Error Video encoding using x265 2.9+9 ----------------

**Video encoding using x265 2.9+9 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: The instruction at 0xp referenced memory at 0xp. The memory could not be s.**
```

I am now using StaxRip 2.0.0.0 Beta 2 for dotNet 4.7
I'm using an Intel Core i9 9900K.
I've tried using different x265 Versions, all for AVX2 enabled.
The only version of x265 that works is x265-2.8+68-fa57fa5_vs2017-AVX2 and previous.
Here's the more extensive error:

```
-------------------------- System Environment --------------------------

StaxRip    : 2.0.0.0
Windows    : Windows 10 Pro 1803
CPU        : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
GPU        : NVIDIA GeForce GTX 1060 6GB
Memory     : 6 GB
Resolution : 1920 x 1080
DPI        : 96

----------------- Process Blu-Ray folder using eac3to -----------------

"C:\Other Apps\StaxRip_2.0.0.0_x64\Apps\eac3to\eac3to.exe" "F:\Lifeforce (1985) - Director's Cut\BDMV\PLAYLIST\"

Source Drive Type: Fixed
1) 00000.mpls, 00000.m2ts, 1:56:14                                             
   - Chapters, 12 chapters                                                     
   - h264/AVC, 1080p24 /1.001 (16:9)                                           
   - DTS Master Audio, English, multi-channel, 48kHz                           

------------------ Process playlist file using eac3to ------------------

"C:\Other Apps\StaxRip_2.0.0.0_x64\Apps\eac3to\eac3to.exe" "F:\Lifeforce (1985) - Director's Cut\BDMV\PLAYLIST\" 1) -progressnumbers

M2TS, 1 video track, 1 audio track, 1 subtitle track, 1:56:14, 24p /1.001      
1: Chapters, 12 chapters                                                       
2: h264/AVC, 1080p24 /1.001 (16:9)                                             
3: DTS Master Audio, English, 5.1 channels, 24 bits, 48kHz                     
   (core: DTS, 5.1 channels, 1509kbps, 48kHz)                                  
4: Subtitle (PGS), English                                                     

--------------------- Demux M2TS using eac3to 3.34 ---------------------

"C:\Other Apps\StaxRip_2.0.0.0_x64\Apps\eac3to\eac3to.exe" "F:\Lifeforce (1985) - Director's Cut\BDMV\PLAYLIST\" 1) 2: "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut.mkv" 3: "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut ID3 English.dtsma" 1: "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut_chapters.txt" 4: "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut ID4 English.sup" -progressnumbers

M2TS, 1 video track, 1 audio track, 1 subtitle track, 1:56:14, 24p /1.001
1: Chapters, 12 chapters
2: h264/AVC, 1080p24 /1.001 (16:9)
3: DTS Master Audio, English, 5.1 channels, 24 bits, 48kHz
(core: DTS, 5.1 channels, 1509kbps, 48kHz)
4: Subtitle (PGS), English
Creating file "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut_chapters.txt"...
v02 Extracting video track number 2...
a03 Extracting audio track number 3...
s04 Extracting subtitle track number 4...
v02 Muxing video to Matroska...
a03 Creating file "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut ID3 English.dtsma"...
s04 Creating file "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut ID4 English.sup"...
Added fps value (24 /1.001) to MKV header.
Video track 2 contains 167205 frames.
Subtitle track 4 contains 1368 captions.
eac3to processing took 6 minutes, 40 seconds.
Done.

Start:    07:19:08
End:      07:25:51
Duration: 00:06:42

------------------------ MediaInfo Source File ------------------------

D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut.mkv

General
Complete name         : D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut.mkv
Format                : Matroska
Format version        : Version 1
File size             : 27.6 GiB
Duration              : 1 h 56 min
Overall bit rate mode : Constant
Overall bit rate      : 34.1 Mb/s
Encoded date          : UTC 2018-12-06 06:19:10
Writing application   : eac3to
Writing library       : Haali DirectShow Matroska Muxer 1.13.138.14
ErrorDetectionType    : Per level 1
CRC_Error_Pos         : 232

Video
ID                    : 1
Format                : AVC
Format/Info           : Advanced Video Codec
Format profile        : High@L4.1
Format settings       : CABAC / 4 Ref Frames
Format, CABAC         : Yes
Format, ReFrames      : 4 frames
Muxing mode           : Container profile=@0.0
Codec ID              : V_MPEG4/ISO/AVC
Duration              : 1 h 56 min
Bit rate mode         : Constant
Bit rate              : 35.0 Mb/s
Width                 : 1 920 pixels
Height                : 1 080 pixels
Display aspect ratio  : 16:9
Frame rate mode       : Constant
Frame rate            : 23.976 (24000/1001) FPS
Color space           : YUV
Chroma subsampling    : 4:2:0
Bit depth             : 8 bits
Scan type             : Progressive
Bits/(Pixel*Frame)    : 0.704
Stream size           : 27.1 GiB (98%)
Default               : No
Forced                : No

------- DGIndexNV: Index, No Demux using DGIndexNV 2053.0.0.161 -------

"C:\Other Apps\DGDecNV_2053.0.0.161\x64 Binaries\DGIndexNV.exe" -i "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut.mkv" -o "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut.dgi" -h

Project

Start:    07:25:52
End:      07:30:02
Duration: 00:04:10

--------------------------- AviSynth Script ---------------------------

Import("C:\Other Apps\StaxRip_2.0.0.0_x64_Beta_2_dotnet4.7\Apps\Plugins\AVS\NNEDI3\edi_rpow2.avsi")
LoadPlugin("C:\Other Apps\StaxRip_2.0.0.0_x64_Beta_2_dotnet4.7\Apps\Plugins\AVS\Shader\Shader.dll")
LoadPlugin("C:\Other Apps\DGDecNV_2053.0.0.162\x64 Binaries\DGDecodeNV.dll")
LoadPlugin("C:\Other Apps\StaxRip_2.0.0.0_x64_Beta_2_dotnet4.7\Apps\Plugins\avs\JPSDR\Plugins_JPSDR.dll")
Import("C:\Other Apps\StaxRip_2.0.0.0_x64_Beta_2_dotnet4.7\Apps\Plugins\AVS\Shader\Shader.avsi")
DGSource("D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut.dgi", i420 = true)
ConvertBits(16)
Crop(0, 132, -0, -132)
SuperResXBR(Passes=5, Factor=4)
Spline64ResizeMT(1920, 816, prefetch = 4)
ConvertBits(10)

-------------------------- Script Properties --------------------------

Source Frame Count : 167205
Source Frame Rate  : 23.976024
Source Duration    : 01:56:13.8420000
Target Frame Count : 167205
Target Frame Rate  : 23.976024
Target Duration    : 01:56:13.8420000

----------------------- MediaInfo Audio Source 1 -----------------------

General
Complete name         : D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut ID3 English.dtsma
Format                : DTS
Format/Info           : Digital Theater Systems
Format profile        : MA / Core
File size             : 1.80 GiB
Overall bit rate mode : Variable / Constant
FileExtension_Invalid : dts dtshd

Audio
Format                : DTS
Format/Info           : Digital Theater Systems
Format profile        : MA / Core
Bit rate mode         : Variable / Constant
Bit rate              : Unknown / 1 509 kb/s
Channel(s)            : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : 24 bits
Compression mode      : Lossless / Lossy

**---------------- Error Video encoding using x265 2.9+9 ----------------

Video encoding using x265 2.9+9 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: The instruction at 0xp referenced memory at 0xp. The memory could not be s.**


------------------- Video encoding using x265 2.9+9 -------------------

"C:\Other Apps\StaxRip_2.0.0.0_x64_Beta_2_dotnet4.7\Apps\avs2pipemod\avs2pipemod64.exe" -y4mp "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut.avs" | "C:\Other Apps\x265\x265-2.9+9-f74003e_vs2015-AVX2\x265.exe" --crf 16 --preset slow --tune grain --level-idc 6.1 --output-depth 10 --analysis-reuse-level 10 --amp --b-intra --cu-lossless --rskip --ssim-rd --qpmax 22 --crf-max 19 --vbv-bufsize 120000 --vbv-maxrate 120000 --cplxblur 0 --aq-motion --subme 4 --weightb --bframes 16 --bframe-bias 100 --rc-lookahead 30 --lookahead-slices 1 --keyint 720 --no-open-gop --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --hash 2 --repeat-headers --hrd --aud --vui-timing-info --vui-hrd-info --opt-qp-pps --opt-ref-list-length-pps --idr-recovery-sei --sao --limit-sao --sao-non-deblock --frames 167205 --y4m --output "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut_out.hevc" -

avs2pipemod[info]: writing 167205 frames of 24000/1001 fps, 1920x816,
sar 0:0, YUV-420-planar-10bit progressive video.
y4m  [info]: 1920x816 fps 24000/1001 i420p10 unknown frame count
raw  [info]: output file: D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut_out.hevc
x265 [info]: HEVC encoder version 2.9+9-f74003e88622
x265 [info]: build info [Windows][MSVC 1900][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-6.1 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(13 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 4 / 3
x265 [info]: Keyframe min / max / scenecut / bias: 23 / 720 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 30 / 16 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 1
x265 [info]: References / ref-limit  cu / depth  : 4 / on / on
x265 [info]: Rate Control / qCompress            : CRF-16.0 / 0.60
x265 [info]: VBV/HRD buffer / max-rate / init    : 120000 / 120000 / 0.900
x265 [info]: tools: rect amp limit-modes rd=4 ssim-rd rdoq=2 psy-rdoq=10.00
x265 [info]: tools: rskip cu-lossless signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=1 deblock sao-non-deblock
avs2pipemod[info]: finished, wrote 58 frames [0%].
avs2pipemod[info]: total elapsed time is 12.117 sec.
avs2pipemod[error]: only wrote 58 of 167205 frames.

------------------- Video encoding using x265 2.9+9 -------------------

"C:\Other Apps\StaxRip_2.0.0.0_x64_Beta_2_dotnet4.7\Apps\avs2pipemod\avs2pipemod64.exe" -y4mp "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut.avs" | "C:\Other Apps\x265\x265-2.9+9-f74003e_vs2015-AVX2\x265.exe" --crf 16 --preset slow --tune grain --level-idc 6.1 --output-depth 10 --analysis-reuse-level 10 --amp --b-intra --cu-lossless --rskip --ssim-rd --qpmax 22 --crf-max 19 --vbv-bufsize 120000 --vbv-maxrate 120000 --cplxblur 0 --aq-motion --subme 4 --weightb --bframes 16 --bframe-bias 100 --rc-lookahead 30 --lookahead-slices 1 --keyint 720 --no-open-gop --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --hash 2 --repeat-headers --hrd --aud --vui-timing-info --vui-hrd-info --opt-qp-pps --opt-ref-list-length-pps --idr-recovery-sei --sao --limit-sao --sao-non-deblock --frames 167205 --y4m --output "D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut_out.hevc" -

avs2pipemod[info]: writing 167205 frames of 24000/1001 fps, 1920x816,
sar 0:0, YUV-420-planar-10bit progressive video.
y4m  [info]: 1920x816 fps 24000/1001 i420p10 unknown frame count
raw  [info]: output file: D:\StaxRip_Temp\Lifeforce (1985) - Director's Cut\Lifeforce (1985) - Director's Cut_out.hevc
x265 [info]: HEVC encoder version 2.9+9-f74003e88622
x265 [info]: build info [Windows][MSVC 1900][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-6.1 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(13 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 4 / 3
x265 [info]: Keyframe min / max / scenecut / bias: 23 / 720 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 30 / 16 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 1
x265 [info]: References / ref-limit  cu / depth  : 4 / on / on
x265 [info]: Rate Control / qCompress            : CRF-16.0 / 0.60
x265 [info]: VBV/HRD buffer / max-rate / init    : 120000 / 120000 / 0.900
x265 [info]: tools: rect amp limit-modes rd=4 ssim-rd rdoq=2 psy-rdoq=10.00
x265 [info]: tools: rskip cu-lossless signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=1 deblock sao-non-deblock
avs2pipemod[info]: finished, wrote 58 frames [0%].
avs2pipemod[info]: total elapsed time is 12.117 sec.
avs2pipemod[error]: only wrote 58 of 167205 frames.

Start:    11:37:54
End:      11:38:07
Duration: 00:00:13
```
