### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by asagichan** [Revan654/staxrip#60]
```

-------------------------- System Environment --------------------------

StaxRip    : 2.0.0.0
Windows    : Windows 10 Pro 1809
Language   : Indonesian (Indonesia)
CPU        : Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
GPU        : Intel(R) HD Graphics 610, NVIDIA GeForce GTX 1050
Resolution : 1366 x 768
DPI        : 96

------------------------ MediaInfo Source File ------------------------

C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3].mkv

General
Complete name           : C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3].mkv
Format                  : Matroska
Format version          : Version 2
File size               : 436 MiB
Duration                : 1 h 30 min
Overall bit rate        : 677 kb/s
Encoded date            : UTC 2018-12-08 03:13:27
Writing application     : mkvmerge v8.5.2 ('Crosses') 32bit
Writing library         : libebml v1.3.3 + libmatroska v1.4.4

Video
ID                      : 1
Format                  : AVC
Format/Info             : Advanced Video Codec
Format profile          : High@L4
Format settings         : CABAC / 6 Ref Frames
Format, CABAC           : Yes
Format, ReFrames        : 6 frames
Codec ID                : V_MPEG4/ISO/AVC
Duration                : 1 h 30 min
Bit rate                : 631 kb/s
Width                   : 1 280 pixels
Height                  : 688 pixels
Display aspect ratio    : 1.85:1
Frame rate mode         : Constant
Frame rate              : 23.976 (24000/1001) FPS
Color space             : YUV
Chroma subsampling      : 4:2:0
Bit depth               : 8 bits
Scan type               : Progressive
Bits/(Pixel*Frame)      : 0.030
Stream size             : 406 MiB (93%)
Writing library         : x264 core 148 r2638 7599210
Default                 : Yes
Forced                  : No

Audio
ID                      : 2
Format                  : AAC
Format/Info             : Advanced Audio Codec
Format profile          : HE-AAC / LC
Format settings         : Explicit
Codec ID                : A_AAC-2
Duration                : 1 h 30 min
Bit rate                : 44.4 kb/s
Channel(s)              : 2 channels
Channel positions       : Front: L R
Sampling rate           : 48.0 kHz / 24.0 kHz
Frame rate              : 23.438 FPS (1024 SPF)
Compression mode        : Lossy
Delay relative to video : 31 ms
Stream size             : 28.6 MiB (7%)
Language                : Japanese
Default                 : Yes
Forced                  : No

----------------- Demux MKV using mkvextract 28.2.0.7 -----------------

"C:\Users\Yosia Kefas\Desktop\All\Staxrip.2.0.0.0.x64\Apps\Support\MKVToolNix\mkvextract.exe" "C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3].mkv" tracks 1:"C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3] ID1 31ms Japanese.aac" --ui-language en

Extracting track 1 with the CodecID 'A_AAC' to the file 'C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3] ID1 31ms Japanese.aac'. Container format: raw AAC file with ADTS headers

Start:    01.34.03
End:      01.34.04
Duration: 00:00:00

General
Complete name         : C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3] ID1 31ms Japanese.aac
Format                : ADTS
Format/Info           : Audio Data Transport Stream
File size             : 29.5 MiB
Overall bit rate mode : Variable

Audio
Format                : AAC
Format/Info           : Advanced Audio Codec
Format version        : Version 4
Format profile        : HE-AAC / LC
Format settings       : Implicit
Bit rate mode         : Variable
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 48.0 kHz / 24.0 kHz
Frame rate            : 23.438 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 29.5 MiB (100%)

------------- Mux AAC to M4A using MP4Box 0.7.2-DEV-rev903 -------------

"C:\Users\Yosia Kefas\Desktop\All\Staxrip.2.0.0.0.x64\Apps\Support\MP4Box\MP4Box.exe" -add "C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3] ID1 31ms Japanese.aac:name= " -new "C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3] ID1 31ms Japanese.m4a"

[32mAAC ADTS import  - sample rate 24000 - MPEG-4 audio - 2 channels
Setting up iTunes/iPod file...
Saving C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3] ID1 31ms Japanese.m4a: 0.500 secs Interleaving

Start:    01.34.04
End:      01.34.06
Duration: 00:00:01


General
Complete name         : C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3] ID1 31ms Japanese.m4a
Format                : MPEG-4
Format profile        : Apple audio with iTunes info
Codec ID              : M4A  (isom/M4A /mp42)
File size             : 29.2 MiB
Duration              : 1 h 30 min
Overall bit rate mode : Variable
Overall bit rate      : 45.3 kb/s
Encoded date          : UTC 2019-01-03 18:34:04
Tagged date           : UTC 2019-01-03 18:34:04

Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : HE-AAC / LC
Format settings       : Implicit
Codec ID              : mp4a-40-2
Duration              : 1 h 30 min
Bit rate mode         : Variable
Bit rate              : 44.4 kb/s
Maximum bit rate      : 61.2 kb/s
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 48.0 kHz / 24.0 kHz
Frame rate            : 23.438 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 28.6 MiB (98%)
Title                 : 
Encoded date          : UTC 2019-01-03 18:34:04
Tagged date           : UTC 2019-01-03 18:34:05

-------------------------- VapourSynth Script --------------------------

import os
import sys
ScriptPath = 'C:/Users/Yosia Kefas/Desktop/All/Staxrip.2.0.0.0.x64/Apps/Plugins/VS/Scripts'
sys.path.append(os.path.abspath(ScriptPath))
import vapoursynth as vs
core = vs.get_core()
core.std.LoadPlugin(r"C:\Users\Yosia Kefas\Desktop\All\Staxrip.2.0.0.0.x64\Apps\Plugins\both\ffms2\ffms2.dll")
core.std.LoadPlugin(r"C:\Users\Yosia Kefas\Desktop\All\Staxrip.2.0.0.0.x64\Apps\Plugins\vs\msmoosh\libmsmoosh.dll")
core.std.LoadPlugin(r"C:\Users\Yosia Kefas\Desktop\All\Staxrip.2.0.0.0.x64\Apps\Plugins\VS\SVPFlow\svpflow1_vs64.dll")
core.std.LoadPlugin(r"C:\Users\Yosia Kefas\Desktop\All\Staxrip.2.0.0.0.x64\Apps\Plugins\VS\SVPFlow\svpflow2_vs64.dll")
clip = core.ffms2.Source(r"C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3].mkv", cachefile = r"C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3].ffindex")
core = vs.get_core(threads=7)

clip = clip.resize.Bicubic(format=vs.YUV420P8)

crop_string  = ""
resize_string = ""
super_params     = "{pel:1,scale:{up:0},gpu:1,full:false,rc:true}"
analyse_params   = "{block:{w:32},main:{search:{coarse:{type:2,distance:-6,bad:{sad:2000,range:24}},type:2}},refine:[{thsad:250}]}"
smoothfps_params = "{gpuid:21,rate:{num:5,den:2},algo:2,mask:{area:200},scene:{}}"

def interpolate(clip):
    input = clip
    if crop_string!='':
        input = eval(crop_string)
    if resize_string!='':
        input = eval(resize_string)

    super   = core.svp1.Super(input,super_params)
    vectors = core.svp1.Analyse(super["clip"],super["data"],input,analyse_params)
    smooth  = core.svp2.SmoothFps(input,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=clip)
    smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)
    return smooth

smooth =  interpolate(clip)

smooth.set_output()
clip = core.msmoosh.MSmooth(clip, threshold = 3.0, strength = 1)

-------------------------- Script Properties --------------------------

Source Frame Count : 129624
Source Frame Rate  : 23.976024
Source Duration    : 01:30:06.4010000
Target Frame Count : 324058
Target Frame Rate  : 59.940060
Target Duration    : 01:30:06.3680000

----------------------- MediaInfo Audio Source 1 -----------------------

General
Complete name         : C:\Users\Yosia Kefas\Documents\Asagi\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3]_temp\[ItoSubs] Liz to Aoi Tori [BD][720p][86EC08F3] ID1 31ms Japanese.m4a
Format                : MPEG-4
Format profile        : Apple audio with iTunes info
Codec ID              : M4A  (isom/M4A /mp42)
File size             : 29.2 MiB
Duration              : 1 h 30 min
Overall bit rate mode : Variable
Overall bit rate      : 45.3 kb/s
Encoded date          : UTC 2019-01-03 18:34:04
Tagged date           : UTC 2019-01-03 18:34:04

Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : HE-AAC / LC
Format settings       : Implicit
Codec ID              : mp4a-40-2
Duration              : 1 h 30 min
Bit rate mode         : Variable
Bit rate              : 44.4 kb/s
Maximum bit rate      : 61.2 kb/s
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 48.0 kHz / 24.0 kHz
Frame rate            : 23.438 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 28.6 MiB (98%)
Title                 : 
Encoded date          : UTC 2019-01-03 18:34:04
Tagged date           : UTC 2019-01-03 18:34:05

------------------------------ Exception ------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.QSVEnc.EncoderParams.OnValueChanged(CommandLineParam item)
   at StaxRip.QSVEnc.Encode()
   at StaxRip.GlobalClass.ProcessVideo()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath)
   at StaxRip.GlobalClass.ProcessJobs()

```
Help wrror cant encode with QSCEnc

**Comment by Revan654** [comment]
There seem to be a bug in QVSEnc, Since some else is having issue with the Encoder as well.

I tweaked some of the code you can re-compile the code and see if it works.

I have no way to debug QVSEnc, The Encoder requires a QS Enabled PC, Which I don't have. The code is untouched from 1.7 there no data saying that the process has changed since then.

You might want to ask the Dev: https://github.com/rigaya/QSVEnc
or at some Encoding forum.

**Comment by woshilaiba** [comment]
there is no problem when use  QVSEnc 3.17  with Staxrip 1.7 on windows10 1809, 
but Staxrip 1.7 not work and show "NullReferenceException" error,
what do you think？
